# import time module, Observer, FileSystemEventHandler

import re
import os

homePath = 'C:' + os.environ['HOMEPATH'].replace('\\','/') + '/'
# homePath = 'C:' + os.environ['HOMEPATH'].replace('\\','/') + '/Desktop/'
publicDownloadsPath = 'C:/Users/Public/Downloads'
needsCorrectionPath = homePath + 'Mustang Plumbing/CAD Plans - General/CAD - WORKING/! - NEEDS CORRECTION'
makeShortcutPath = homePath + 'Mustang Plumbing/CAD Plans - General/CAD - WORKING/- SCRIPT FOLDERS/(0) - MAKE SHORTCUT'
checkScriptPath = homePath + 'Mustang Plumbing/CAD Plans - General/CAD - WORKING/- SCRIPT FOLDERS/(1) - CHECK SCRIPT'
moveToFinishedPath = homePath + 'Mustang Plumbing/CAD Plans - General/CAD - WORKING/- SCRIPT FOLDERS/(2) - MOVE TO FINISHED'

cadInProgressPath = homePath + 'Mustang Plumbing/CAD Plans - General/CAD - WORKING/0 - IN PROGRESS'
readyToCheckPath = homePath + 'Mustang Plumbing/CAD Plans - General/CAD - WORKING/1 - READY TO CHECK'          #Note: full path will include /DRAWN BY <AUTHOR>, instead of /AUTHOR
checkInProgressPath = homePath + 'Mustang Plumbing/CAD Plans - General/CAD - WORKING/2 - CHECK IN PROGRESS'
finishedFromCADPath = homePath + 'Mustang Plumbing/CAD Plans - General/FINISHED FROM CAD'

cadDWGsPath = 'S:/CAD/Plans'

builderCorrectSpellings = {
    'ARBOGAST CUSTOM': 'ARBOGAST',
    'DAVID WEEKLY': 'DAVID WEEKLEY',
    'EMPIRE': 'EMPIRE-CENTERRA',
    'CENTERRA': 'EMPIRE-CENTERRA',
    'IN TOWN': 'INTOWN HOMES',
    'INTOWN': 'INTOWN HOMES',
    'IN TOWN HOMES': 'INTOWN HOMES',
    'PNL BUILDERS': 'PNL',
    'PNL HOMES': 'PNL',
    'VALE BUILDER GROUP': 'VALE',
    'SYMCOX':'MICHAUX SYMCOX'
}

builderPaths = {
    'ALEXANDER HOMES': {'FFC':'Alexander Homes',
            'DWG':'ALEXANDER HOMES/AUTOCAD DWGS'},
    'ARBOGAST': {'FFC':'Arbogast Custom',
            'DWG':'ARBOGAST/AUTOCAD DWGS'},
	'ASH CREEK': {'FFC':'Ash Creek',
            'DWG':'ASH CREEK/AUTOCAD DWGS'},
    'ASHTON WOODS': {'FFC': 'Miscellaneous',
            'DWG': 'ASHTON WOODS/AUTOCAD DWGS'},
    'BACCUS JACKSON': {'FFC':'Baccus Jackson',
            'DWG':'BACCUS JACKSON/AUTOCAD DWGS'},
    'BLACKBURN': {'FFC':'Blackburn',
            'DWG':'BLACKBURN/AUTOCAD DWGS'},
    'BOLES CONSTRUCTION': {'FFC':'Boles Construction',
            'DWG':'BOLES CONSTRUCTION/AUTOCAD DWGS'},
    'BOLIN STEGER': {'FFC':'Miscellaneous',
            'DWG':'BOLIN STEGER/AUTOCAD DWGS'},
    'BROHN': {'FFC':'Brohn',
            'DWG':'BROHN/AUTOCAD DWGS'},
    'BUNKER RANCH': {'FFC':'Bunker Ranch',
            'DWG':'BUNKER RANCH/AUTOCAD DWGS'},
    'C2 CUSTOM BUILDING': {'FFC':'C2 Custom Building',
            'DWG':'C2 CUSTOM BUILDING, LLC/AUTOCAD DWGS'},
    'CALEDONIA': {'FFC':'Caledonia',
            'DWG':'CALEDONIA/AUTOCAD DWGS'},
    'CANTON': {'FFC':'Miscellaneous',
            'DWG':'CANTON/AUTOCAD DWGS'},
    'CASTLEROCK': {'FFC':'Castlerock',
            'DWG':'CASTLEROCK/AUTOCAD DWGS'},
    'CHESMAR': {'FFC':'Chesmar',
            'DWG':'CHESMAR/AUTOCAD DWGS'},
    'COBALT': {'FFC':'Cobalt',
            'DWG':'_OLD BUILDERS/COBALT COMPANIES'},
    'CORDSEN CONST': {'FFC':'Cordsen Const',
            'DWG':'_OLD BUILDERS/CORDSEN CONSTRUCTION LLC'},
    'CORNERSTONE': {'FFC': 'Miscellaneous',
            'DWG':'CORNERSTONE/AUTOCAD DWGS'},
    'CROSSVINE': {'FFC':'Crossvine',
            'DWG':'CROSSVINE/AUTOCAD DWGS'},
    'DANNEN DEVELOP': {'FFC':'Dannen Develop',
            'DWG':'DANNEN DEVELOP/AUTOCAD DWGS'},
    'DAVID WEEKLEY': {'FFC':'David Weekley',
            'DWG':'DAVID WEEKLEY/AUTOCAD DWGS'},
    'DESIGN VISIONS': {'FFC':'Miscellaneous',
            'DWG':'DESIGN VISIONS/AUOCAD DWGS'},
    'DH HOMES': {'FFC':'DH Homes',
            'DWG':'DH HOMES/AUTOCAD DWGS'},
    'DR HORTON': {'FFC':'DR Horton',
            'DWG':'DR HORTON/AUTOCAD DWGS'},
    'DREAM FINDERS': {'FFC':'Dream Finders',
            'DWG':'DREAM FINDERS/AUTOCAD DWGS'},
    'DREES': {'FFC':'Drees',
            'DWG':'DREES/AUTOCAD DWGS'},
    'DREW HOMES': {'FFC':'Drew Homes',
            'DWG':'DREW HOMES/AUTOCAD DWGS'},
    'EMPIRE-CENTERRA': {'FFC':'Empire - CENTERRA',
            'DWG':'EMPIRE-CENTERRA/AUTOCAD DWGS'},
    'GARRETT SIGNATURE': {'FFC':'Garrett Signature',
            'DWG':'JAY GARRETT SIGNATURE HOMES/AUTOCAD DWGS'},
    'GEHAN': {'FFC':'Gehan',
            'DWG':'GEHAN/AUTOCAD DWGS'},
    'GESHKE': {'FFC':'Miscellaneous',
            'DWG':'GESHKE GROUP/AUTOCAD DWGS'},
    'GFO': {'FFC':'GFO',
            'DWG':'GFO/AUTOCAD DWGS'},
    'GRAND ENDEAVOR': {'FFC':'Grand Endeavor',
            'DWG':'GRAND ENDEAVOR/AUTOCAD DWGS'},
    'HABITAT HAUS': {'FFC':'Habitat Haus',
            'DWG':'_OLD BUILDERS/HABITAT HAUS/AUTOCAD DWGS'},
    'HARBOR': {'FFC':'Miscellaneous',
            'DWG':'HARBOR/AUTOCAD DWGS'},
    'HERRADURA': {'FFC':'Miscellaneous',
            'DWG':'HERRADURA'},
    'HARDIN MARIE': {'FFC':'Hardin Marie',
            'DWG':'_OLD BUILDERS/HARDIN MARIE'},
    'HARLAN MAC': {'FFC':'Harlan Mac',
            'DWG':'_OLD BUILDERS/HARLAN MAC/AUTOCAD DWGS'},
    'HAYDEN HOMES': {'FFC':'Hayden Homes',
            'DWG':'_OLD BUILDERS/HAYDEN HOMES'},
    'HIGHLAND': {'FFC':'Highland',
            'DWG':'HIGHLAND/AUTOCAD DWGS'},
    'HILL COUNTRY ARTISAN': {'FFC':'Hill Country Artisan',
            'DWG':'HILL COUNTRY ARTISAN/AUTOCAD DWGS'},
    'INTOWN HOMES': {'FFC':'InTown Homes',
            'DWG':'IN TOWN HOMES/AUTOCAD DWGS'},
    'JEFF SMITH':{'FFC':'Miscellaneous',
            'DWG':'JEFF SMITH/AUTOCAD DWGS'},
    'JENKINS DESIGN BUILD': {'FFC':'Jenkins Design Build',
            'DWG':'_OLD BUILDERS/JENKINS DESIGN+BUILD'},
    'JIMMY JACOBS':{'FFC':'Miscellaneous',
            'DWG':'JIMMY JACOBS CONSTRUCTION'},
    'KILIGRAY': {'FFC':'Kiligray',
            'DWG':'_OLD BUILDERS/KILIGRAY/AUTOCAD DWGS'},
    'LAUREL HAVEN HOMES': {'FFC':'Laurel Haven Homes',
            'DWG':'LAUREL HAVEN HOMES/AUTOCAD DWGS'},
    'LEGACY MCS': {'FFC':'Legacy MCS',
            'DWG':'_OLD BUILDERS/LEGACY/AUTOCAD DWGS'},
    'LEGEND': {'FFC':'Legend Comm HDJS',
            'DWG':'LEGEND COMMUNITIES/AUTOCAD DWGS'},
    'LIVING PROOF': {'FFC':'Miscellaneous',
            'DWG':'LIVING PROOF CONSTRUCTION/AUTOCAD DWGS'},
    'LTX': {'FFC':'LTX',
            'DWG':'LTX CUSTOM HOMES/AUTOCAD DWGS'},
    'MAGNETS REI': {'FFC':'Magnets REI',
            'DWG':'_OLD BUILDERS/MAGNETS REI/AUTOCAD DWGS'},
    'MANNA CUSTOMS': {'FFC':'Manna Customs',
            'DWG':'MANNA CUSTOMS/AUTOCAD DWGS'},
    'MENFI': {'FFC':'Menfi',
            'DWG':'_OLD BUILDERS/MENFI'},
    'MERITAGE': {'FFC':'Meritage',
            'DWG':'MERITAGE/AUTOCAD DWGS'},
    'MHI': {'FFC':'MHI',
            'DWG':'MHI HOMEBUILDERS/AUTOCAD DWGS'},
    'MICHAUX SYMCOX': {'FFC':'Michaux Symcox',
            'DWG':'SYMCOX/AUTOCAD DWGS'},
    'MIKE WELLS': {'FFC':'Miscellaneous',
            'DWG':'MIKE WELLS'},
    'MILESTONE': {'FFC':'Milestone',
            'DWG':'MILESTONE COMMUNITY BUILDERS/AUTOCAD DWGS'},
    'MIRASOL': {'FFC':'Miscellaneous',
            'DWG':'MIRASOL HOMES/AUTOCAD DWGS'},
    'MISCELLANEOUS': {'FFC':'Miscellaneous',
            'DWG':'MISC/AUTOCAD DWGS'},
    'MISSION HOMES': {'FFC':'Mission Homes',
            'DWG':'_OLD BUILDERS/MISSION HOMES BUILDERS/AUTOCAD DWGS'},
    'MODERN HOMESTEAD': {'FFC':'Modern Homestead',
            'DWG':'MODERN HOMESTEAD/AUTOCAD DWGS'},
    'MONTICELLO': {'FFC':'Monticello',
            'DWG':'MONTICELLO/AUTOCAD DWGS'},
    'MWS': {'FFC':'Miscellaneous',
            'DWG':'MWS/AUTOCAD DWGS'},
    'NOVAK BROS': {'FFC':'Novak Bros',
            'DWG':'_OLD BUILDERS/NOVAK/AUTOCAD DWGS'},
    'PACESETTER': {'FFC':'Pacesetter',
            'DWG':'PACESETTER/AUTOCAD DWGS'},
    'PACIFIC IMAGE': {'FFC':'Pacific Image',
            'DWG':'_OLD BUILDERS/PACIFIC IMAGE BUILDERS/AUTOCAD DWGS'},
    'PERRY': {'FFC':'Perry',
            'DWG':'PERRY HOMES/AUTOCAD DWGS'},
    'PINNACLE CUSTOM': {'FFC':'Pinnacle Custom',
            'DWG':'_OLD BUILDERS/PINNACLE CUSTOM HOMES'},
    'PNL': {'FFC':'PNL Builders',
            'DWG':'PNL HOMES/AUTOCAD DWGS'},
    'PSW': {'FFC':'PSW',
            'DWG':'PSW HOMES/AUTOCAD DWGS'},
    'PULTE': {'FFC':'Pulte',
            'DWG':'PULTE GROUP/AUTOCAD DWGS'},
    'RIVENDALE': {'FFC':'Miscellaneous',
            'DWG':'RIVENDALE/AUTOCAD DWGS'},
    'SAN GABRIEL': {'FFC':'San Gabriel',
            'DWG':'_OLD BUILDERS/SAN GABRIEL BUILDERS/AUTOCAD DWGS'},
    'SARATOGA': {'FFC':'Saratoga',
            'DWG':'SARATOGA/AUTOCAD DWGS'},
    'SCOTT FELDER': {'FFC':'Scott Felder',
            'DWG':'SCOTT FELDER/AUTOCAD DWGS'},
    'SENDERO': {'FFC':'Sendero',
            'DWG':'SENDERO/AUTOCAD DWGS'},
    'SILAS LACEY': {'FFC':'Miscellaneous',
            'DWG':'SILAS LACEY/AUTOCAD DWGS'},
    'SITTERLE': {'FFC':'Sitterle',
            'DWG':'SITTERLE/AUTOCAD DWGS'},
    'SMYTH REAL ESTATE': {'FFC':'Smyth Real Estate',
            'DWG':'_OLD BUILDERS/SMYTH RESIDENTIAL/AUTOCAD DWGS'},
    'STARLIGHT': {'FFC':'Starlight',
            'DWG':'STARLIGHT/AUTOCAD DWGS'},
    'STORYBUILT': {'FFC':'Storybuilt',
            'DWG':'PSW/AUTOCAD DWGS'},
    'TAYLOR MORRISON': {'FFC':'Taylor Morrison',
            'DWG':'TAYLOR MORRISON/AUTOCAD DWGS'},
    'THOMAS AHRENS': {'FFC':'Miscellaneous',
            'DWG':'THOMAS AHRENS/AUTOCAD DWGS'},
    'TKF HOMES': {'FFC':'TKF Homes',
            'DWG':'_OLD BUILDERS/TKF CUSTOM HOMES/AUTOCAD DWGS'},
    'TOLL BROS': {'FFC':'Toll Bros',
            'DWG':'TOLL BROTHERS/AUTOCAD DWGS'},
    'TYLER SELVAGE': {'FFC':'Miscellaneous',
            'DWG':'TYLER SELVAGE/AUTOCAD DWGS'},
    'URBAN ATX': {'FFC':'Urban ATX',
            'DWG':'URBAN ATX/AUTOCAD DWGS'},
    'VALE': {'FFC':'Vale Builder Group',
            'DWG':'VALE/AUTOCAD DWGS'},
    'VINTAGE ESTATES': {'FFC':'Vintage Estates',
            'DWG':'VINTAGE ESTATES/AUTOCAD DWGS'},
    'WESTIN': {'FFC':'Westin',
            'DWG':'WESTIN HOMES/AUTOCAD DWGS'},
    'WESTWOOD CUSTOM': {'FFC':'Miscellaneous',
            'DWG':'WESTWOOD CUSTOM/AUTOCAD DWGS'},
    'WILLIAMS': {'FFC':'Williams',
            'DWG':'WILLIAMS HOMES/AUTOCAD DWGS'}
}

watchedDirectories = [needsCorrectionPath,
                      makeShortcutPath,
                      checkScriptPath,
                      moveToFinishedPath]

pdfBrickRegex = re.compile("^(?!OLD)(.*BRK-.*)\.pdf$")
oldPdfBrickRegex = re.compile("^OLD.*BRK-.*\.pdf$")
builderRegex = re.compile(".*BRK-([^-]*)-")
dwgBrickRegex = re.compile(".*BRK.*\.dwg$")

suffixList = ['-LANDSCAPE',
                '-LEFT',
                '-L',
                '-RIGHT',
                '-R']